.\" $Id$
.Dd January 12, 2007
.Dt XT3DMON 1
.ds volume Pittsburgh Supercomputing Center
.\" .ds vT Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm xt3dmon
.Nd graphical XT3 monitor
.Sh SYNOPSIS
.Nm xt3dmon
.Op Fl dMp
.Op Fl c Ar machconf
.Op Fl H Ar height
.Op Fl W Ar width
.Op Fl U Ar urispec
.Op Fl x Ar dxscript
.Sh DESCRIPTION
.Nm
is a
.Tn 3D
program that graphically displays various data sets of
information about the BigBen Cray
.Tn XT3
cluster.
Data about the cluster nodes are read at startup and can be continually
refreshed so that the display reflects reality.
.Pp
The command-line options are as follows:
.Bl -tag -width Ds
.\" .It Fl a
.\" Enable active stereo mode.
.\" In this mode, if the video hardware supports it,
.\" .Nm
.\" will manage buffers for both the left and right eyes to be
.\" overlaid on the same window.
.It Fl c Ar machconf
Specify an alternative
.Pa mach.conf
machine description file.
Default is
.Pa data/mach.conf .
See
.Sx MACH.CONF FORMAT
below for more information on this file.
.It Fl d
Enable
.Dq daemon
mode \(em that is,
.Nm
will listen on
.Tn TCP
connections to accept requests from clients to generate screen captures
and send the resulting images as responses.
.It Fl H Ar height
Specify the
.Nm
window height in pixels.
.It Fl M
Start the
.Nm
window in full-screen (maximized) mode.
.It Fl p
Enable passive stereo mode.
In this mode, two windows are created and maintained individually,
for use by a stereo projector overlaying the right side of the
available screen space with the left.
.It Fl W Ar width
Specify the
.Nm
window width in pixels.
.It Fl U Ar urispec
Set the data source
.Tn URI Ns s
according to the given
.Ar urispec .
The specification will be copied to each live data source retrieval
.Tn URI
with any
.Sq %s
replaced with the data source's name (e.g.
.Dq node
or
.Dq job ) .
Defaults to:
.Pp
.D1 gssapi://bigben-monitor.psc.edu/arbiter-raw.pl?data=%s
.It Fl x Ar dxscript
Load and run
.Ar dxscript
at startup.
See
.Sx Deus Ex\& Mode
below.
.El
.Pp
There are a number of different data displays available:
job, yod, temperature, seastar counters, lustre status,
and various routing statistics
(see the key assignments below for how to enable these modes).
Each mode assigns every cluster node a color corresponding to its
status with respect to that display mode.
.Pp
In the job and yod modes, cluster nodes may be in any of the following
states, differentiated by color/texture:
.Pp
.Bl -tag -width "Disabled (PBS)" -offset indent -compact
.It Free
The node is available to run jobs.
.It Disabled (PBS)
The node is not being used to run jobs via
.Tn PBS .
.It Down (CPA)
The node is marked down by
.Tn CPA .
.It Used
A job is assigned to and is running on the node.
These nodes are colored by their respective job.
.It Service
The node is a service node, not a compute node.
.El
.Pp
The temperature mode colors each cluster node according to its nearest
temperature class range.
.Pp
The seastar and routing error modes color the nodes based upon the
relative performance of each node to the rest of the nodes.
.Pp
Some modes, such as job mode, provide sensitive job details from the
.Tn XT3
system.
As such, accessing this information requires authenticating with a
valid
.Tn PSC Ns /Kerberos
account, which can be set with the
.Ic pL
command and will only be used over an
.Tn OpenSSL
connection.
.Pp
The legend panel (see the
.Ic pl
command) displays all possible node states for the current data
viewing mode.
Each state is accompanied by a color box representing the color in
which nodes of that state will be drawn.
Using the
.Ic + , - , = ,
and
.Ic _
keys over the label will modify the translucency of that node class.
.Pp
The following is a quick reference of the most useful key bindings:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It left, right, up, down
Pan the camera to the left, right, forward, or backward along its
view.
.Pp
If the cursor is over a panel widget that is a part of a logical
collection of related widgets, the camera will not be moved and
instead an adjacent panel widget will become checked.
.Pp
.It home, end
.Dq Barrel roll
the camera to the left or right.
.Pp
.It pageup, pagedown
Pan the camera up and down along (perpendicular to) its view.
.Pp
.It left click
Click a node for extended information.
Hold shift and click to toggle the selected state of additional nodes.
.Pp
Click, hold, and drag the mouse to revolve around the point of focus,
normally the cluster view.
.Pp
While holding the shift key, click, hold, and drag the mouse to freely
adjust the camera view.
.Pp
.It Ic 2 , 4 , 6 , 8
Revolve around the point of focus.
.Pp
.It Ic aj
Display only nodes in jobs of any selected nodes.
.Pp
.It Ic O
Move the camera to a bird's eye view of the cluster.
.Pp
.It Ic p0
Hide all panels.
.Pp
.It Ic pa
Toggle all non-interactive panels.
.Pp
.It Ic q
Quit.
.Pp
.It Ic [x , [y , [z , [[
.It Ic ]x , ]y , ]z , ]]
Adjust the wired cluster viewing mode node spacing factor.
.Pp
.It Xo
.Ic {x , {y , {z ,
.Ic {0 , {{
.Xc
.It Xo
.Ic }x , }y , }z ,
.Ic }0 , }}
.Xc
Adjust the wired cluster viewing mode node offset factor.
The key sequences involving zero reset the offset.
.Pp
.It Ic + , _ , = , -
Adjust translucency for the node class under the cursor of the
legend panel.
.El
.Pp
The following additional key bindings are also available:
.Bl -tag -width Ds -offset indent
.It Ic ^A
Select all visible nodes.
.It Ic ar
Display all nodes.
.It Ic as
Display only selected nodes.
.\" .It Ic C
.\" Redraw the cluster.
.It Ic c
Clear the selected node(s).
.It Ic fc
Empty the flyby data file.
By default, enabling recording consecutively will append flyby states to
the file.
.It Ic fl
Toggle the looping of flyby playback.
.It Ic fp
Playback a previously recorded flyby.
Press
.Em space
.Bk -words
.Pq Dq " "
.Ek
to toggle suspension of playback.
Press any other key to break out of playback.
.It Ic fq
Toggle the recording and saving of the live state, for use in flyby
playbacks.
.It Ic I
Toggle the cluster subset membership of all selected nodes.
When the subset option is enabled, only nodes in the subset will be
shown.
.It Ic i
Print the node
.Tn ID Ns s
(nids) of all selected nodes to standard output.
.It Ic kd
Restore the arrow keys to camera movement (see
.Ic kn
below).
.It Ic kn
Remap the arrow keys to move about the neighbors of any selected nodes.
.Pp
While holding shift, neighbors in the direction of the key pressed will
be selected additionally instead of in place of the currently selected
nodes.
.It Ic kw
Remap the arrow keys to modify the wired cluster viewing mode node
offset factor.
.It Ic L
Load the list of previously saved selected nodes.
See the
.Ic S
command.
.It Ic M
Maximize window.
.It Ic mj
Switch to job data mode (default).
.It Ic mt
Switch to temperature data mode.
.It Ic my
Switch to yod data mode.
.It Ic oC
Toggle the display of node CPU cores.
.It Ic od
Toggle screen capture.
Files with sequenced names are written into the
.Pa snaps
directory.
.It Ic oe
Toggle movement interpolation
.Pq Dq tweening .
.It Ic oG
Toggle the frame rate governor.
.It Ic og
Toggle display of the ground and axes.
.It Ic ol
Toggle the display of node labels.
.It Ic oM
Toggle the display of modules.
.It Ic on
Toggle node animation for when nodes move positions.
.It Ic oP
Toggle the display of pipes to the wired neighbors of any selected nodes.
.It Ic op
Toggle the display of pipes to the wired neighbors of all nodes.
.It Ic os
Toggle skeleton mode.
.It Ic ot
Toggle texture mapping.
.It Ic ow
Toggle the display of wireframes around nodes.
.It Ic ^Pr
Color node pipes according to interconnection router errors.
.It Ic ^Pd
Color node pipes according to interconnection torus.
.It Ic pB
Toggle the flyby creator panel.
.It Ic pb
Toggle the flyby chooser panel.
.It Ic pC
Toggle the compass panel.
.\" .It Ic pc
.\" Toggle the command panel.
.It Ic pD
Toggle the data mode selector panel.
.It Ic pd
Toggle the date/time panel.
.It Ic pF
Toggle the flyby overview panel.
.It Ic pf
Toggle the frames-per-second panel.
.It Ic pg
Toggle the goto-node panel.
Enter a node ID (nid) to move to that node.
.It Ic ph
Toggle the help panel.
.It Ic pj
Toggle the goto-job panel.
Enter a job ID to view only that job.
.It Ic pk
Toggle the keyboard remapping control panel.
.It Ic pL
Toggle the login panel.
Prompts for a username and password to access job details.
.It Ic pl
Toggle the legend panel.
.It Ic pm
Toggle the interconnect coloring (pipe) mode panel.
.It Ic pn
Toggle the extended node information panel.
.It Ic po
Toggle the option panel.
.It Ic pP
Toggle the
.Dq panels
panel \(em one panel to rule them all.
.It Ic pp
Toggle the camera position panel.
.It Ic pR
Toggle the routing-mode control panel.
.It Ic pr
Toggle the archive/reel chooser panel.
.It Ic pS
Toggle the status panel.
.It Ic ps
Toggle the screenshot panel.
The
.Em tab
key will temporarily hide this panel when it is open,
useful generating screenshots without the panel itself
being shown.
.It Ic pt
Toggle the SeaStar-mode control panel.
.It Ic pV
Toggle the view mode selector panel.
.It Ic pw
Toggle the wired-mode control panel.
.It Ic px
Toggle the Deus Ex script chooser panel.
.It Ic pz
Toggle the custom dataset chooser panel.
.It Ic ^Q Ns Ar n
Save the current camera position into the hotkey
.Ar n ,
which may be in the range
.Bq 0 , Ns 9 .
.It Ic ^W Ns Ar n
Load the hotkey camera position
.Ar n .
.It Ic R
Refresh current data set.
.It Ic r+ , r- , rr
Cycle through the port sets in the routing error data mode.
.It Ic rR , rF , rT
Change the routing error data mode to display recoverable, fatal,
or router errors.
.It Ic S
Save the list of currently selected nodes for later restoration via the
.Ic L
command.
.It Ic vn
Switch to the wired job neighbor mode.
In this mode, nodes within a job are drawn according to proximity to
their neighbors, with the selected node at the center.
.It Ic vo
Switch to the wired viewing mode with only one cluster drawn.
.It Ic vp
Switch to the physical viewing mode (default).
.It Ic vw
Switch to the wired viewing mode with the cluster drawn continuously.
.It Ic x
Toggle
.Em Deus Ex\&
mode.
See below.
.El
.Sh DEUS EX MODE
.Nm
can have many of its actions scripted by loading a
.Em deus ex
script and running it with the Deus Ex mode.
The syntax and grammar for these scripts are as follows.
.Pp
Empty lines and lines beginning with a
.Sq #
are ignored.
All other lines must contain one action directive,
which may be any of the following:
.Bl -tag -width Ds
.It Ic bird
Move to a bird's eye view.
.It Xo
.Ic camlook
.Fa x , Ns Fa y , Ns Fa z
.Xc
Set the camera look vector to
.Po
.Fa x , Ns Fa y , Ns Fa z
.Pc .
.It Xo
.Ic campos
.Fa x , Ns Fa y , Ns Fa z
.Xc
Set the camera position vector to
.Po
.Fa x , Ns Fa y , Ns Fa z
.Pc .
.It Xo
.Ic camuprot
.Fa r
.Xc
Set the camera up rotation in radians.
.It Ic clrsn
Clear any selected nodes.
.It Ic corkscrew Ar dim
Steer the camera along a corkscrew path through the cluster.
.Ar dim
specifies along which dimension the path should be made and may be one
of
.Ic x , y ,
or
.Ic z .
.It Ic cuban8 Ar dim
Steer the camera along a cuban-8 path through the cluster.
.Ar dim
specifies along which dimension the path should be made and may be one
of
.Ic x , y ,
or
.Ic z .
.It Xo
.Ic curlyq Ar dim
.Op Ar frac Op Ar nsecs
.Xc
The same as
.Ic orbit
except that the camera continually moves closer to the point of focus
throughout the revolutions.
See
.Ic orbit
for details on the arguments.
.It Ic cyclenc Op Ar method
Cycle through each node class (such as jobs or temperature range)
of the current data mode, displaying only one class at a time.
.Ar method
may be
.Ic cycle
(default if unspecified) or
.Ic grow .
.It Ic dmode Ar dm
Set the data mode.
Recognized values for
.Ar dm
are
.Ic job , temp , rte ,
and
.Ic yod .
.It Xo
.Ic focus
.Fa x , Ns Fa y , Ns Fa z
.Xc
Set the camera focus point to
.Po
.Fa x , Ns Fa y , Ns Fa z
.Pc .
During camera movement, this point will always be centered in view.
.It Ic hl Ar class
Highlight (i.e., only show) nodes in given node
.Ar class .
The following symbolic names are recognized:
.Pp
.Bl -tag -offset indent -width 10n -compact
.It Ic all
Show all node classes.
.It Ic seldm
Show all node classes of any selected node.
.El
.It Ic move Ar dir amt Op Ar nsecs
Pan the camera in the given direction
.Ar dir
the given amount
.Ar amt .
.Ar dir
may be one of
.Ic forward , back .
.Ar amt
is a floating-point or integer number of 3-space units.
.Ar nsecs
specifies the number of seconds to make the displacement over.
.It Xo
.Ic opt
.Op Ar modifier
.Ar option Op , Ar ...
.Xc
Change the view options.
.Ar modifier
may be
.Sq + ,
which enables options,
.Sq - ,
which disables options, or left blank, which sets all current
options to only those specified.
.Pp
The following options are recognized:
.Pp
.Bl -tag -width 10n -offset indent -compact
.It Ic cabskel
Include cabinents in skeletons.
.It Ic caption
Show captions.
.It Ic forcefocus
During camera movement, view the
.Ic focus
point.
.It Ic frames
Show node wireframes.
.It Ic ground
Show the ground/axes.
.It Ic modskel
Include blades in skeletons.
.It Ic nlabels
Node labels.
.It Ic nodeanim
Animate node movement.
.It Ic pause
Pause until disabled (e.g. by pressing
.Em space ) .
.It Ic pipes
Show pipes representing node interconnections.
.It Ic selnlbls
Node labels for selected nodes.
.It Ic selpipes
Show interconnect pipes for selected nodes.
.It Ic skel
Cluster skeletons.
.It Ic subset
Show only sub-selected nodes (see
.Ic subsel ) .
.It Ic tex
Use textures of solid colors for node fills.
.It Ic tween
Smooth camera movement with
.Dq tween steps.
.El
.Pp
Example:
.Bd -literal -offset Ds
# have only these options set
opt frames,nlabels

# disable these options
opt -skel,selpipes
.Ed
.It Xo
.Ic orbit Ar dim
.Op Ar frac Op Ar nsecs
.Xc
Orbit the current focus point, which will be the center of all
selected nodes, if there are any, or otherwise the entire cluster
view.
.Ar dim
specifies which dimension (e.g.,
.Ic x , y ,
or
.Ic z )
and may be prefixed with a minus sign
.Pq Sq -
to specify reverse revolutions.
.Ar frac
specifies the number of revolutions to make, which may be specified as a
floating-point number, and defaults to one if unspecified.
.Ar nsecs
specifies the number of seconds over which to make the orbit,
which may be specified as a floating-point number, and is calculated to
be set
.Dq comfortably
according to distance from the focal point if unspecified.
.Pp
Example:
.Bd -literal -offset Ds
# orbit x-dimension twice over 10 seconds
orbit -x 2.0 10.0

# simple half-circle orbit
orbit +x 0.5
.Ed
.It Xo
.Ic panel
.Op Ar modifier
.Ar panel Op , Ar ...
.Xc
Change which panels are shown.
.Ar modifier
may be
.Sq + ,
which enables panels,
.Sq - ,
which disables panels, or left blank, which makes
.Nm
show only the specified panels.
.Pp
The following panels are available:
.Pp
.Bl -tag -width 10n -offset indent -compact
.It Ic cam
Camera position.
.\" .It Ic cmd
.\" Execute command on login node.
.It Ic compass
Compass.
.It Ic date
date/time of dataset.
.It Ic dmode
Data mode selector.
.It Ic dscho
Custom/archive data set chooser.
.It Ic dxcho
Deus-ex script chooser.
.\" .It Ic eggs
.It Ic fbcho
Flyby chooser.
.It Ic fbcreat
Interactive Flyby creator.
.It Ic fbstat
Flyby controls.
.It Ic fps
Frames-per-second meter.
.It Ic gotojob
Interactive go-to job controls.
.It Ic gotonode
Interactive go-to node controls.
.It Ic help
Help.
.It Ic keyh
Keyboard remapping controls.
.It Ic legend
Node class legend.
.It Ic login
Login for accessing job details.
.It Ic ninfo
Information about selected node(s).
.It Ic options
Program option controls.
.It Ic panels
Panel controls.
.It Ic pipe
Pipe mode controls.
.It Ic reel
Archive reel selector.
.It Ic rt
Route-mode controls.
.It Ic sshot
Interactive screenshot saver.
.It Ic sstar
Seastar-mode controls.
.It Ic status
Program status information.
.It Ic vmode
View mode selector.
.It Ic wiadj
Wired-mode spacing controls.
.El
.Pp
Example:
.Bd -literal -offset Ds
# display only these panels
panel vmode,dmode,legend

# enable these panels
panel +status,vmode,wiadj
.Ed
.It Ic playreel Ar delay archive
Play a data archive reel.
Each frame is shown for
.Ar delay
milliseconds.
.Ar archive
specifies the reel directory and must be surrounding by double quote
characters
.Pq Dq .
.It Xo
.Ic pstick
.Ar stick
.Ar panel Op , Ar ...
.Xc
Change the panel
.Dq stick
i.e. position of the given panels.
Recognized
.Ar stick
values are:
.Pp
.Bl -tag -width 10n -offset indent -compact
.It Ic tl
Top-left.
.It Ic tr
Top-right.
.It Ic bl
Bottom-left.
.It Ic br
Bottom-right.
.El
.Pp
Example:
.Bd -literal -offset Ds
# move legend and node info to top-left corner
pstick tl legend,ninfo
.Ed
.It Ic refocus
Move the camera view to point to the current focus, which will
be the center of all selected nodes, if there are any, or otherwise
the entire cluster view.
.It Ic refresh
Grab new data.
.It Ic seljob random
Select a random job-allocated node and highlight its respective job.
.It Xo
.Ic selnode
.Op Ar modifier
.Dq Ar nid Op , Ar ...
.Xc
Modify the participation of the node with the given node ID
.Ar nid
in the current selection.
Multiple
.Ar nid
arguments may be specified, separated by commas, with no intervening
whitespace.
The double quote characters
.Pq Dq
are always required and will result in parse errors if unspecified.
.Pp
.Ar modifier
may be
.Sq + ,
which adds the specified nodes to the current selection,
.Sq - ,
which removes the specified nodes from the current selection,
of left blank, which makes the current selection consist of only the
nodes specified.
.Pp
The following
.Ar nid
pseudo-classes are also recognized:
.Pp
.Bl -tag -width "visibleX" -offset Ds -compact
.It Ic all
All visible nodes will be chosen.
.It Ic random
A node will be chosen at random.
.It Ic visible
All visible nodes will be chosen.
.El
.It Ic setcap Ar caption
If the caption option is enabled, the caption displayed will be
changed to the given
.Ar caption .
Captions may be optionally surrounded by double quotes
.Pq Dq \&
to allow spaces.
.It Ic ssctl Ar type value
Set the value of a SeaStar-mode control.
Recognized types and their values are:
.Bl -tag -offset indent -width Ds
.It Ic vc
Set the SeaStar
.Tn VC
being viewed to one of
.Ic 0 , 1 , 2 ,
or
.Ic 3 .
.It Ic mode
Set which SeaStar counter value to display.
May be one of
.Ic blocked , packets ,
or
.Ic flits .
.El
.It Ic stall Ar nsecs
Remain still for the specified number of seconds
.Ar nsecs ,
which may be a floating-point number.
.It Xo
.Ic subsel
.Op Ar modifier
.Dq Ar nid Op , Ar ...
.Xc
Modify the participation of the node with the given node ID
.Ar nid
in the current cluster subset.
Multiple
.Ar nid
arguments may be specified, separated by commas, with no intervening
whitespace.
The double quote characters
.Pq Dq
are always required and will result in parse errors if unspecified.
.Pp
.Ar modifier
may be
.Sq + ,
which adds the specified nodes to the current subset,
.Sq - ,
which removes the specified nodes from the current subset,
of left blank, which makes the current subset consist of only the
nodes specified.
.Pp
The following
.Ar nid
pseudo-classes are also recognized:
.Pp
.Bl -tag -width "visibleX" -offset Ds -compact
.It Ic all
All visible nodes will be chosen.
.It Ic random
A node will be chosen at random.
.It Ic selected
All selected nodes will be chosen.
.It Ic visible
All visible nodes will be chosen.
.El
.Pp
Only nodes in the current subset will be visible when the
.Em subset
option is enabled.
.It Ic vmode Ar vm
Set the current cluster view mode.
Recognized values for
.Ar vm
are
.Ic phys , wione ,
and
.Ic wired .
.It Ic winsp Ar x y z
Set the wired-mode node spacing factor.
Each of
.Ar x , y ,
or
.Ar z
may be prefixed by a
.Sq + ,
which will increase the spacing by the given factor,
.Sq - ,
which will decrease the spacing factor, or nothing, in which case the
spacing factor for that dimension will be set to the given value.
.It Ic wioff Ar x y z
Set the wired-mode node offset.
Each of
.Ar x , y ,
or
.Ar z
may be prefixed by a
.Sq + ,
which will increase the offset,
.Sq - ,
which will decrease the offset, or nothing, in which case the
offset in that dimension will be set to the given value.
.El
.Sh MACH.CONF FORMAT
The
.Pa mach.conf
file is used to describe the cluster's characteristics including
physical node layout and wired dimensions.
The syntax and grammar for this file is as follows.
.Pp
Empty lines and lines beginning with a
.Sq #
are ignored.
All other lines must contain one variable definition,
which may be any of the following:
.Bl -tag -width Ds
.It Ic coredim Aq Ar x , y , z
Specify the layout of node CPU cores.
For example, the value
.Dq 1,1,2
specifies a total of
.Pq 1 * 1 * 2
= 2 cores with one core spread across the X distance, one core spread
across the Y distance, and two cores spread across the Z distance of a
node.
.It Ic cubedim Aq Ar x , y , z
Specify the wired node dimension bounds.
.It Ic nidmax Ar n
Specify the maximum (exclusive) node ID
.Pq Dq nid .
.It Ic dim Ar name Li { ... }
Specify a physical dimension.
Each dimension block may contain the following directives:
.Bl -tag -width
.It Ic contains Ar name
Specify parent/child relationship of dimensions.
There must be a direct relationship (i.e. all dimensions are contained
by one and only one parent dimension) of all dimensions specify in
.Pa mach.conf .
The innermost dimension is specified implicitly by not having
.Ic contains
directive.
.It Ic skel Ar bool
Specify whether skeleton outlines of this dimension should
be drawn when the skeleton outline option is enabled within
.Nm .
.Ar bool
may be
.Ic yes
or
.Ic no .
.It Ic mag Ar n
Specifies the magnitude, or number, of occurrences, of this
dimension with respect to its parent dimension.
.It Ic offset Aq Ar x , y , z
Specifies the XYZ offset applied to subsequent reoccurances of this
dimension.
.It Ic size Aq Ar x , y , z
Specifies the size of this dimension.
.It Ic space Ar n
Specifies the spacing between occurances of this dimension
within its parent dimension.
Spacing can only be applied to the XYZ dimension a physical
dimension spans (see the
.Ic spans
directive).
.It Ic spans Ar dim
Specify with XYZ dimension this physical dimension spans across.
.Ar dim
may be
.Ic x , y ,
or
.Ic z .
.El
.El
.Sh DATA FILES
.Nm
gathers its data from the following files, accessed through the
URI specification set by the
.Fl U
flag:
.Pp
.Bl -tag -width Pa -compact
.It Pa node
node information
.It Pa job
job information
.It Pa yod
yod information
.It Pa ss
SeaStar register data
.It Pa rt
.Xr xtnetwatch 1
routing error data
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa img/font.png
font texture used for node labels
.It Pa img/tex-sc Ns Em %d Ns Pa .png
node state textures
.It Pa img/tex-selnode.png
selected node texture
.It Pa data/archive/
default archive index directory
.It Pa data/colors
job color table
.It Pa data/flybys/
flyby data files
.It Pa data/flybys/default
default flyby file
.It Pa data/hotkey- Ns Em %c
hotkey camera positions
.It Pa data/latest-archive
default archive reel directory
.It Pa data/mach.conf
machine description file
.It Pa data/selnids
saved selected node ID list
.It Pa scripts/
default deus-ex script directory
.It Pa snaps/ Ns Em %08d Ns Pa .png
capture output files
.It Pa /tmp/xtsess/
server-mode client sessions
.El
.Sh COPYRIGHT
Copyright
.Pq c
2005-2007 Pittsburgh Supercomputing Center
http://www.psc.edu/
.Pp
Distributed binaries contain and/or are linked with the following bits
of software and their respective licenses:
.Pp
.Bl -tag -width freeglutX -offset indent -compact
.It libpng
http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-10
.It zlib
http://www.zlib.net/zlib_license.html
.It freeglut
http://www.opensource.org/licenses/mit-license.php
.It openssl
http://www.openssl.org/source/license.html
.El
