.\" $Id$
.Dd February 1, 2006
.Dt XT3DMON 1
.ds volume Pittsburgh Supercomputing Center
.\" .ds vT Pittsburgh Supercomputing Center
.Os http://www.psc.edu/
.Sh NAME
.Nm xt3dmon
.Nd XT3 monitor
.Sh SYNOPSIS
.Nm xt3dmon
.Op Fl dp
.Op Fl c Ar physconf
.Sh DESCRIPTION
.Nm
is a 3D program that graphically displays various data sets of
information about the BigBen Cray
.Tn XT3
cluster.
Data about the cluster nodes are read at startup and can be continually
refreshed so that the display reflects reality.
.Pp
The options are as follows:
.Bl -tag -width Ds
.\" .It Fl a
.\" Enable active stereo mode.
.\" In this mode, if the video hardware supports it,
.\" .Nm
.\" will manage buffers for both the left and right eyes to be
.\" overlaid on the same window.
.It Fl c Ar physconf
Specify an alternative
.Pa phys.conf
machine physical layout description file.
Default is
.Pa data/phys.conf .
.It Fl d
Enable
.Dq daemon
mode \(em that is,
.Nm
will listen on TCP connections to accept requests from clients to
generate screen captures and send the resulting images as
responses.
.It Fl p
Enable passive stereo mode.
In this mode, two windows are created and maintained individually,
for use by a stereo projector overlaying the right side of the
available screen space with the left.
.El
.Pp
There are four different data displays available: job, yod, temperature,
and failure information (see the key assignments below for how to enable
these modes).
Each mode assigns every cluster node a color corresponding to its
status with respect to that display mode.
.Pp
In job mode, cluster nodes may be in any of the following states,
differentiated by color/texture:
.Pp
.Bl -tag -width "Disabled (PBS)" -offset indent -compact
.It Free
The node is available to run jobs.
.It Disabled (PBS)
The node is not being used to run jobs via PBS.
.It Down (CPA)
The node is marked down by CPA.
.It Used
A job is assigned to and is running on the node.
These nodes are colored by their respective job.
.It Service
The node is a service node, not a compute node.
.El
.Pp
The yod mode acts similarily but instead shows yod instead of job
information about the used nodes.
.Pp
The failure and temperature modes color each cluster node according to
its respective failure statistics or temperature.
.Pp
Some modes gather and display information about user accounts on the
XT3 system.
As such, accessing this information requires authenticating with a
valid PSC/Kerberos account, which can be set with the
.Ic pL
command.
.Pp
The legend panel (see the
.Ic pl
command) displays all possible node states for the currently selected
data viewing mode.
.Pp
The following key bindings are available:
.Bl -tag -width Ds -offset indent
.It left, right, up, down
Pan the camera to the left, right, forward, or backward along its
view.
.It home, end
.Dq Barrel roll
the camera to the left or right.
.It pageup, pagedown
Pan the camera up and down along (perpendicular to) its view.
.It left click
Click a node for extended information.
Hold shift and click to add nodes to the selection.
Hold control and click to remove nodes from the selection.
.Pp
Click, hold, and drag the mouse to revolve around the cluster view.
.Pp
While holding the shift key, click, hold, and drag the mouse to freely
adjust the camera view.
.It Ic ad
Display only PBS-disabled nodes.
.It Ic af
Display only free (i.e., no job running) nodes.
.It Ic aj
Display only nodes in jobs of any selected nodes.
.It Ic ar
Restore display of all nodes.
.It Ic as
Display only selected nodes.
.It Ic C
Redraw the cluster.
.It Ic c
Clear the selected node(s).
.It Ic fc
Empty the flyby data file.
By default, enabling recording consecutively will append flyby states to
the file.
.It Ic fl
Toggle the looping of flyby playback.
.It Ic fp
Playback a previously recorded flyby.
Press any key to break out of playback mode.
.It Ic fq
Toggle the recording and saving of the live state, for use in flyby
playbacks.
.It Ic kd
Restore the arrow keys to camera movement (see
.Ic kn
below).
.It Ic kn
Remap the arrow keys to move about the neighbors of any selected nodes.
.Pp
While holding shift, neighbors in the direction of the key pressed will
be selected additionally instead of in place of the currently selected
nodes.
.It Ic mf
Switch to failure data mode.
.It Ic mj
Switch to job data mode (default).
.It Ic mt
Switch to temperature data mode.
.It Ic my
Switch to yod data mode.
.It Ic O
Move the camera to a bird's eye view of the cluster.
.It Ic oD
Toggle drawing to the screen.
.It Ic od
Toggle screen capture.
Files with sequenced names are written into the
.Pa snaps
directory.
.It Ic oe
Toggle movement interpolation
.Pq Dq tweening .
.It Ic of
Toggle the display of cluster frames in wired view.
.It Ic oG
Toggle the frame rate governor.
.It Ic og
Toggle display of the ground and axes.
.It Ic ol
Toggle the display of node labels.
.It Ic oM
Toggle the display of modules.
.It Ic on
Toggle node animation for when nodes move positions.
.It Ic oP
Toggle the display of pipes to the wired neighbors of any selected nodes.
.It Ic op
Toggle the display of pipes to the wired neighbors of all nodes.
.It Ic os
Toggle skeleton mode.
.It Ic ot
Toggle texture mapping.
.It Ic ow
Toggle the display of wireframes around nodes.
.It Ic pa
Toggle all non-interactive panels.
.\" .It Ic pc
.\" Toggle the command panel.
.It Ic pd
Toggle the date/time panel.
.It Ic pF
Toggle the flyby overview panel.
.It Ic pf
Toggle the frames-per-second panel.
.It Ic pg
Toggle the goto-node panel.
Enter a node ID (nid) to move to that node.
.It Ic pj
Toggle the goto-job panel.
Enter a job ID to view only that job.
.It Ic pL
Toggle the login panel.
Prompts for a username/password combination to access account-specific
information.
.It Ic pl
Toggle the legend panel.
.It Ic pm
Toggle the memory usage panel.
.It Ic pn
Toggle the extended node information panel.
.It Ic po
Toggle the option panel.
.It Ic pp
Toggle the camera position panel.
.It Ic pS
Toggle the status panel.
.It Ic ps
Toggle the screenshot panel.
.It Ic q
Quit.
.It Ic R
Refresh current data set.
.It Ic vo
Switch to the wired viewing mode with only one cluster drawn.
.It Ic vp
Switch to the physical viewing mode (default).
.It Ic vw
Switch to the wired viewing mode with the cluster drawn continuously.
.It Xo
.Ic [x , [y , [z ,
.Ic [[ ,
.Ic ]x , ]y , ]z ,
.Ic ]]
.Xc
Adjust the wired cluster viewing mode node spacing factor.
.It Xo
.Ic {x , {y , {z ,
.Ic {0 , {{ ,
.Ic }x , }y , }z ,
.Ic }0 , }}
.Xc
Adjust the wired cluster viewing mode node offset factor.
The key sequences involving zero reset the offset.
.It Ic + , _
Adjust job node translucency.
.It Ic = , -
Adjust other node translucency.
.El
.Sh FILES
.Bl -tag -width Pa -compact
.It Pa img/texture Ns Em %d Ns Pa .png
node state textures
.It Pa img/font.png
font texture used for node labels
.It Pa data/phys.conf
cluster physical description file
.It Pa data/node
node information
.It Pa data/job
job information
.It Pa data/yod
yod information
.It Pa data/flyby.data
flyby data file
.It Pa snaps/ Ns Em %08d Ns Pa .png
capture output files
.El
