#!/bin/sh
# $Id$

unset DISPLAY

start()
{
	sudo -u xt3dmon startx -- :9 &
}

stop()
{
	pkill -u xt3dmon startx
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	echo "usage: $0 start|stop|restart"
	;;
esac
